// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/services/data_companion/v1/data_companion.proto

package v1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SetRetainHeightRequest allows the data companion to indicate to the node the
// height to which it is safe to prune from the perspective of the companion.
type SetRetainHeightRequest struct {
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *SetRetainHeightRequest) Reset()         { *m = SetRetainHeightRequest{} }
func (m *SetRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SetRetainHeightRequest) ProtoMessage()    {}
func (*SetRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8180275a1308d9, []int{0}
}
func (m *SetRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRetainHeightRequest.Merge(m, src)
}
func (m *SetRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRetainHeightRequest proto.InternalMessageInfo

func (m *SetRetainHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetRetainHeightResponse struct {
}

func (m *SetRetainHeightResponse) Reset()         { *m = SetRetainHeightResponse{} }
func (m *SetRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*SetRetainHeightResponse) ProtoMessage()    {}
func (*SetRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8180275a1308d9, []int{1}
}
func (m *SetRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRetainHeightResponse.Merge(m, src)
}
func (m *SetRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRetainHeightResponse proto.InternalMessageInfo

type GetRetainHeightRequest struct {
}

func (m *GetRetainHeightRequest) Reset()         { *m = GetRetainHeightRequest{} }
func (m *GetRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetRetainHeightRequest) ProtoMessage()    {}
func (*GetRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8180275a1308d9, []int{2}
}
func (m *GetRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRetainHeightRequest.Merge(m, src)
}
func (m *GetRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRetainHeightRequest proto.InternalMessageInfo

type GetRetainHeightResponse struct {
	// The retain height previously set by the data companion, if any.
	DataCompanionRetainHeight int64 `protobuf:"varint,1,opt,name=data_companion_retain_height,json=dataCompanionRetainHeight,proto3" json:"data_companion_retain_height,omitempty"`
	// The retain height set by the application.
	AppRetainHeight int64 `protobuf:"varint,2,opt,name=app_retain_height,json=appRetainHeight,proto3" json:"app_retain_height,omitempty"`
}

func (m *GetRetainHeightResponse) Reset()         { *m = GetRetainHeightResponse{} }
func (m *GetRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetRetainHeightResponse) ProtoMessage()    {}
func (*GetRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8180275a1308d9, []int{3}
}
func (m *GetRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRetainHeightResponse.Merge(m, src)
}
func (m *GetRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRetainHeightResponse proto.InternalMessageInfo

func (m *GetRetainHeightResponse) GetDataCompanionRetainHeight() int64 {
	if m != nil {
		return m.DataCompanionRetainHeight
	}
	return 0
}

func (m *GetRetainHeightResponse) GetAppRetainHeight() int64 {
	if m != nil {
		return m.AppRetainHeight
	}
	return 0
}

// StoredDataCompanionRetainConfig is the on-disk representation of the data
// companion's retention configuration.
type StoredDataCompanionRetainConfig struct {
	// The retain height as desired by the data companion.
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *StoredDataCompanionRetainConfig) Reset()         { *m = StoredDataCompanionRetainConfig{} }
func (m *StoredDataCompanionRetainConfig) String() string { return proto.CompactTextString(m) }
func (*StoredDataCompanionRetainConfig) ProtoMessage()    {}
func (*StoredDataCompanionRetainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8180275a1308d9, []int{4}
}
func (m *StoredDataCompanionRetainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredDataCompanionRetainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredDataCompanionRetainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredDataCompanionRetainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredDataCompanionRetainConfig.Merge(m, src)
}
func (m *StoredDataCompanionRetainConfig) XXX_Size() int {
	return m.Size()
}
func (m *StoredDataCompanionRetainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredDataCompanionRetainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StoredDataCompanionRetainConfig proto.InternalMessageInfo

func (m *StoredDataCompanionRetainConfig) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*SetRetainHeightRequest)(nil), "tendermint.services.data_companion.v1.SetRetainHeightRequest")
	proto.RegisterType((*SetRetainHeightResponse)(nil), "tendermint.services.data_companion.v1.SetRetainHeightResponse")
	proto.RegisterType((*GetRetainHeightRequest)(nil), "tendermint.services.data_companion.v1.GetRetainHeightRequest")
	proto.RegisterType((*GetRetainHeightResponse)(nil), "tendermint.services.data_companion.v1.GetRetainHeightResponse")
	proto.RegisterType((*StoredDataCompanionRetainConfig)(nil), "tendermint.services.data_companion.v1.StoredDataCompanionRetainConfig")
}

func init() {
	proto.RegisterFile("tendermint/services/data_companion/v1/data_companion.proto", fileDescriptor_6c8180275a1308d9)
}

var fileDescriptor_6c8180275a1308d9 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x2a, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6,
	0x4f, 0x49, 0x2c, 0x49, 0x8c, 0x4f, 0xce, 0xcf, 0x2d, 0x48, 0xcc, 0xcb, 0xcc, 0xcf, 0xd3, 0x2f,
	0x33, 0x44, 0x13, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x45, 0xe8, 0xd5, 0x83, 0xe9,
	0xd5, 0x43, 0x53, 0x59, 0x66, 0xa8, 0x64, 0xc0, 0x25, 0x16, 0x9c, 0x5a, 0x12, 0x94, 0x5a, 0x92,
	0x98, 0x99, 0xe7, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22,
	0x24, 0xc6, 0xc5, 0x96, 0x01, 0x16, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x94,
	0x24, 0xb9, 0xc4, 0x31, 0x74, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x49, 0x70, 0x89, 0xb9,
	0x63, 0x35, 0x4c, 0xa9, 0x8d, 0x91, 0x4b, 0xdc, 0x1d, 0xbb, 0x2e, 0x21, 0x7b, 0x2e, 0x19, 0x54,
	0x77, 0xc5, 0x17, 0x81, 0x95, 0xc5, 0xa3, 0x58, 0x2f, 0x09, 0x52, 0xe3, 0x0c, 0x53, 0x82, 0x6c,
	0x90, 0x90, 0x16, 0x97, 0x60, 0x62, 0x41, 0x01, 0x9a, 0x2e, 0x26, 0xb0, 0x2e, 0xfe, 0xc4, 0x82,
	0x02, 0x64, 0xb5, 0x4a, 0x96, 0x5c, 0xf2, 0xc1, 0x25, 0xf9, 0x45, 0xa9, 0x29, 0x2e, 0x98, 0xc6,
	0x39, 0xe7, 0xe7, 0xa5, 0x65, 0xa6, 0xe3, 0xf2, 0xb8, 0x53, 0xda, 0x89, 0x47, 0x72, 0x8c, 0x17,
	0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c,
	0x37, 0x1e, 0xcb, 0x31, 0x44, 0xf9, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0x23, 0x45, 0x19, 0x12, 0x13, 0x1c, 0x27, 0xfa, 0x44, 0x45, 0x67, 0x12, 0x1b, 0x58, 0xb1,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x84, 0xbe, 0x1a, 0xde, 0xfe, 0x01, 0x00, 0x00,
}

func (m *SetRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintDataCompanion(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AppRetainHeight != 0 {
		i = encodeVarintDataCompanion(dAtA, i, uint64(m.AppRetainHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.DataCompanionRetainHeight != 0 {
		i = encodeVarintDataCompanion(dAtA, i, uint64(m.DataCompanionRetainHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StoredDataCompanionRetainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredDataCompanionRetainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredDataCompanionRetainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintDataCompanion(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDataCompanion(dAtA []byte, offset int, v uint64) int {
	offset -= sovDataCompanion(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SetRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovDataCompanion(uint64(m.Height))
	}
	return n
}

func (m *SetRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DataCompanionRetainHeight != 0 {
		n += 1 + sovDataCompanion(uint64(m.DataCompanionRetainHeight))
	}
	if m.AppRetainHeight != 0 {
		n += 1 + sovDataCompanion(uint64(m.AppRetainHeight))
	}
	return n
}

func (m *StoredDataCompanionRetainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovDataCompanion(uint64(m.Height))
	}
	return n
}

func sovDataCompanion(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDataCompanion(x uint64) (n int) {
	return sovDataCompanion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SetRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDataCompanion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataCompanion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDataCompanion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataCompanion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDataCompanion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataCompanion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataCompanionRetainHeight", wireType)
			}
			m.DataCompanionRetainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataCompanionRetainHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppRetainHeight", wireType)
			}
			m.AppRetainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppRetainHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDataCompanion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataCompanion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredDataCompanionRetainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredDataCompanionRetainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredDataCompanionRetainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDataCompanion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataCompanion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDataCompanion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDataCompanion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDataCompanion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDataCompanion
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDataCompanion
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDataCompanion
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDataCompanion        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDataCompanion          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDataCompanion = fmt.Errorf("proto: unexpected end of group")
)
