// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/services/block/v1/block_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("tendermint/services/block/v1/block_service.proto", fileDescriptor_1488dadaa3ae41e3)
}

var fileDescriptor_1488dadaa3ae41e3 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x28, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6,
	0x4f, 0xca, 0xc9, 0x4f, 0xce, 0xd6, 0x2f, 0x33, 0x84, 0x30, 0xe2, 0xa1, 0xe2, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x32, 0x08, 0x1d, 0x7a, 0x30, 0x1d, 0x7a, 0x60, 0x85, 0x7a, 0x65, 0x86,
	0x52, 0x1a, 0x84, 0xcd, 0x83, 0x98, 0x63, 0xd4, 0xc6, 0xcc, 0xc5, 0xe3, 0x04, 0xe2, 0x07, 0x43,
	0x94, 0x09, 0xb5, 0x32, 0x72, 0x09, 0xb8, 0xa7, 0x96, 0xf8, 0x24, 0x96, 0xa4, 0x16, 0x97, 0x80,
	0x65, 0x3c, 0x5d, 0x84, 0x4c, 0xf5, 0xf0, 0x59, 0xa7, 0x87, 0xae, 0x3e, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x44, 0xca, 0x8c, 0x54, 0x6d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0x0c, 0x06,
	0x8c, 0x42, 0xd9, 0x5c, 0x1c, 0xee, 0xa9, 0x10, 0x19, 0x21, 0x5d, 0x82, 0xe6, 0x80, 0xd5, 0xc1,
	0xac, 0xd5, 0x23, 0x56, 0x39, 0xcc, 0x3a, 0xa1, 0x06, 0x46, 0x2e, 0x7e, 0x24, 0xe1, 0xd2, 0x9c,
	0x92, 0x62, 0x21, 0x13, 0xa2, 0x4d, 0x01, 0x29, 0x87, 0xd9, 0x6d, 0x4a, 0xa2, 0x2e, 0x98, 0x13,
	0x9c, 0x62, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09,
	0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x39, 0x3d, 0xb3,
	0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x29, 0x5e, 0x91, 0x98, 0xe0, 0xa8, 0xd4,
	0xc7, 0x17, 0xe7, 0x49, 0x6c, 0x60, 0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x56,
	0x0f, 0x8d, 0x6a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockServiceClient is the client API for BlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockServiceClient interface {
	// GetLatestBlockID returns a stream of the latest block IDs as they are
	// committed by the network.
	GetLatestBlockID(ctx context.Context, in *GetLatestBlockIDRequest, opts ...grpc.CallOption) (BlockService_GetLatestBlockIDClient, error)
	// GetBlock attempts to retrieve the block at a particular height,
	// including all of its transactions.
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	// GetBlockResults attempts to retrieve the results of block execution for
	// a particular height, including all events and transaction execution
	// results.
	GetBlockResults(ctx context.Context, in *GetBlockResultsRequest, opts ...grpc.CallOption) (*GetBlockResultsResponse, error)
}

type blockServiceClient struct {
	cc grpc1.ClientConn
}

func NewBlockServiceClient(cc grpc1.ClientConn) BlockServiceClient {
	return &blockServiceClient{cc}
}

func (c *blockServiceClient) GetLatestBlockID(ctx context.Context, in *GetLatestBlockIDRequest, opts ...grpc.CallOption) (BlockService_GetLatestBlockIDClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlockService_serviceDesc.Streams[0], "/tendermint.services.block.v1.BlockService/GetLatestBlockID", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockServiceGetLatestBlockIDClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockService_GetLatestBlockIDClient interface {
	Recv() (*GetLatestBlockIDResponse, error)
	grpc.ClientStream
}

type blockServiceGetLatestBlockIDClient struct {
	grpc.ClientStream
}

func (x *blockServiceGetLatestBlockIDClient) Recv() (*GetLatestBlockIDResponse, error) {
	m := new(GetLatestBlockIDResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blockServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/tendermint.services.block.v1.BlockService/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockServiceClient) GetBlockResults(ctx context.Context, in *GetBlockResultsRequest, opts ...grpc.CallOption) (*GetBlockResultsResponse, error) {
	out := new(GetBlockResultsResponse)
	err := c.cc.Invoke(ctx, "/tendermint.services.block.v1.BlockService/GetBlockResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockServiceServer is the server API for BlockService service.
type BlockServiceServer interface {
	// GetLatestBlockID returns a stream of the latest block IDs as they are
	// committed by the network.
	GetLatestBlockID(*GetLatestBlockIDRequest, BlockService_GetLatestBlockIDServer) error
	// GetBlock attempts to retrieve the block at a particular height,
	// including all of its transactions.
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	// GetBlockResults attempts to retrieve the results of block execution for
	// a particular height, including all events and transaction execution
	// results.
	GetBlockResults(context.Context, *GetBlockResultsRequest) (*GetBlockResultsResponse, error)
}

// UnimplementedBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockServiceServer struct {
}

func (*UnimplementedBlockServiceServer) GetLatestBlockID(req *GetLatestBlockIDRequest, srv BlockService_GetLatestBlockIDServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLatestBlockID not implemented")
}
func (*UnimplementedBlockServiceServer) GetBlock(ctx context.Context, req *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (*UnimplementedBlockServiceServer) GetBlockResults(ctx context.Context, req *GetBlockResultsRequest) (*GetBlockResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockResults not implemented")
}

func RegisterBlockServiceServer(s grpc1.Server, srv BlockServiceServer) {
	s.RegisterService(&_BlockService_serviceDesc, srv)
}

func _BlockService_GetLatestBlockID_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestBlockIDRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockServiceServer).GetLatestBlockID(m, &blockServiceGetLatestBlockIDServer{stream})
}

type BlockService_GetLatestBlockIDServer interface {
	Send(*GetLatestBlockIDResponse) error
	grpc.ServerStream
}

type blockServiceGetLatestBlockIDServer struct {
	grpc.ServerStream
}

func (x *blockServiceGetLatestBlockIDServer) Send(m *GetLatestBlockIDResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BlockService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.services.block.v1.BlockService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockService_GetBlockResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetBlockResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.services.block.v1.BlockService/GetBlockResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetBlockResults(ctx, req.(*GetBlockResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.services.block.v1.BlockService",
	HandlerType: (*BlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _BlockService_GetBlock_Handler,
		},
		{
			MethodName: "GetBlockResults",
			Handler:    _BlockService_GetBlockResults_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLatestBlockID",
			Handler:       _BlockService_GetLatestBlockID_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tendermint/services/block/v1/block_service.proto",
}
